name: TruffleHog OSS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        head: ${{ github.event.pull_request.head.sha || github.sha }}
        base: ${{ github.event.pull_request.base.sha || github.event.before || 'HEAD~1' }}
        extra_args: --results=verified,unknown 