name: TruffleHog OSS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    name: Scan repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for TruffleHog to scan git history
          fetch-tags: true

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          head: ${{ github.event.pull_request.head.sha || github.sha }}
          base: ${{ github.event.pull_request.base.sha || github.event.before || 'HEAD~1' }}
          extra_args: --only-verified --no-verification 